# Generated by Django 4.0.6 on 2022-09-18 18:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRblogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='extended_user',
            name='user_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_img'),
        ),
    ]
