# Generated by Django 4.0.6 on 2022-09-24 09:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRblogs', '0002_alter_blog_post_post_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='main_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
