# Generated by Django 4.0.6 on 2022-09-24 10:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRblogs', '0003_alter_blog_post_main_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='main_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
