# Generated by Django 4.0.6 on 2022-10-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRblogs', '0005_blog_post_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='post_url',
        ),
    ]
