# Generated by Django 4.0.6 on 2022-10-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRblogs', '0007_blog_post_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='post_url',
            field=models.CharField(default='URL will be gererated after saving record', max_length=120),
        ),
    ]
