# Generated by Django 4.0.6 on 2022-09-18 18:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portpolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='about',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='doc'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='img'),
        ),
    ]
