# Generated by Django 4.0.6 on 2022-10-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portpolio', '0002_alter_about_image_alter_about_resume_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
